import type { FeedPost } from "~/components/FeedCard";

export const PLACEHOLDER_POSTS: FeedPost[] = [
  {
    id: "p1",
    author: "Maya Builds",
    authorInitials: "MB",
    authorColor: "#FF6B2B",
    timestamp: "2 minutes ago",
    content:
      "Just launched my handmade candle shop on SpinCity and already got 12 follows in an hour! This community is unreal. If you're an entrepreneur tired of big-platform ad prices — you belong here.",
    category: "Entrepreneur",
    categoryVariant: "primary",
    likes: 47,
    comments: 9,
    shares: 5,
    cardTint: "rgba(255,107,43,0.04)",
  },
  {
    id: "p2",
    author: "Jax The Creator",
    authorInitials: "JC",
    authorColor: "#7C3AED",
    timestamp: "14 minutes ago",
    content:
      "Design tip: your logo doesn't need to be perfect to start. Mine was made in Canva on a Saturday. Three years later it's still the same logo — and people love it. Ship first, refine later. 🚀",
    imageUrl: undefined, // no image card
    category: "Design",
    categoryVariant: "secondary",
    likes: 134,
    comments: 22,
    shares: 41,
    cardTint: "rgba(124,58,237,0.04)",
  },
  {
    id: "p3",
    author: "Tara Designs",
    authorInitials: "TD",
    authorColor: "#0EA5E9",
    timestamp: "31 minutes ago",
    content:
      "Running ads on the old platforms was burning $400/month for almost zero conversions. SpinCity's flat-rate model changed everything. First month: 3 real clients. No joke.",
    category: "Growth",
    categoryVariant: "accent",
    likes: 89,
    comments: 17,
    shares: 28,
    cardTint: "rgba(14,165,233,0.04)",
  },
  {
    id: "p4",
    author: "Founder Felix",
    authorInitials: "FF",
    authorColor: "#10B981",
    timestamp: "1 hour ago",
    content:
      "Poll: What's your biggest pain point as an early-stage founder?\n\n🔥 Finding customers\n💸 Managing cash flow\n📣 Marketing on a budget\n🤝 Building the right team\n\nDrop your answer below — building something to help!",
    category: "Startup",
    categoryVariant: "primary",
    likes: 203,
    comments: 58,
    shares: 34,
  },
  {
    id: "p5",
    author: "SpinCity Nina",
    authorInitials: "SN",
    authorColor: "#F59E0B",
    timestamp: "2 hours ago",
    content:
      "Posted my first reel-style video here and it already has 200 views. The algorithm actually shows content to people who want to see it? What a concept.",
    imageUrl: "",  // image placeholder shown
    category: "Creator",
    categoryVariant: "secondary",
    likes: 61,
    comments: 11,
    shares: 7,
    cardTint: "rgba(245,158,11,0.04)",
  },
  {
    id: "p6",
    author: "Hustler Leo",
    authorInitials: "HL",
    authorColor: "#EC4899",
    timestamp: "3 hours ago",
    content:
      "Quick thread on pricing your services without underselling yourself 👇\n\n1/ Stop charging hourly — charge for outcomes.\n2/ Your price is a signal of your value.\n3/ Clients who haggle the most are usually the worst to work with.\n4/ Double your rate. You'll lose some leads and gain better clients.",
    category: "Business",
    categoryVariant: "accent",
    likes: 312,
    comments: 44,
    shares: 99,
  },
  {
    id: "p7",
    author: "Crea8or Vee",
    authorInitials: "CV",
    authorColor: "#FF6B2B",
    timestamp: "5 hours ago",
    content:
      "New merch drop for my brand is live! Hand-drawn illustrations, limited run. Every purchase supports an indie designer — that's me 👋. Link in bio.",
    imageUrl: "",  // placeholder image
    category: "Creator",
    categoryVariant: "primary",
    likes: 78,
    comments: 13,
    shares: 21,
    cardTint: "rgba(255,107,43,0.04)",
  },
  {
    id: "p8",
    author: "BizWiz Sam",
    authorInitials: "BS",
    authorColor: "#7C3AED",
    timestamp: "6 hours ago",
    content:
      "If you're a small business owner and you're not email marketing, you're leaving serious money on the table. Your email list is the only audience you truly own. Start building it today — even 200 engaged subscribers > 10k cold followers.",
    category: "Marketing",
    categoryVariant: "secondary",
    likes: 157,
    comments: 29,
    shares: 63,
    cardTint: "rgba(124,58,237,0.04)",
  },
];
